theme = "personal-blog-theme"
languageCode = "en-us"
baseurl = "http://example.com/"
title = "Tailwinds Blog Theme"

author = "Alok Regmi"
copyright = "Copyright © 2021, Alok Regmi, all rights reserved."

[params]
    name = "Tailwinds Blog Theme"
    description = "A simple bootstraped theme for Hugo, build with Tailwindcss."

    github_user = "dragarok"
    github_repo = "https://github.com/dragarok/personal-blog-theme"
    github_banner = true

    favicon = "favicon.ico"

[build]
  writeStats = true

# syntax highlight settings
[markup]
  [markup.highlight]
    style = "dracula"
